---
- name: 'Install packages'
  package:
    name: 'nginx'

- name: 'Ensure base config files'
  template:
    src: "{{ file }}.j2"
    dest: "/etc/nginx/{{ file }}"
    mode: 0644
  loop:
    - 'nginx.conf'
    - 'acme.conf'
  loop_control:
    loop_var: 'file'
  notify: 'reload nginx'

- name: 'Ensure DHparams'
  openssl_dhparam:
    path: '/etc/nginx/dhparams.pem'
    size: "{{ nginx_dhparams_size }}"
    mode: 0644
    owner: 'root'
    group: 'root'

- name: 'Ensure service'
  service:
    name: 'nginx'
    state: 'started'
    enabled: true

- name: 'Install app config file'
  template:
    src: "{{ app.type }}.conf.j2"
    dest: "/etc/nginx/sites-enabled/{{ app.name }}.conf"
    mode: 0644
  loop: "{{ nginx_apps | default([]) }}"
  loop_control:
    loop_var: 'app'
  notify: 'reload nginx'
  when: app.state == 'present'

- name: 'Remove app config file'
  file:
    path: "/etc/nginx/sites-enabled/{{ app.name }}.conf"
    state: 'absent'
  loop: "{{ nginx_apps | default([]) }}"
  loop_control:
    loop_var: 'app'
  notify: 'reload nginx'
  when: app.state == 'absent'
