---
- name: 'Converge'
  hosts: 'all'
  tasks:
    - name: 'Update cache'
      apt:
        update_cache: true
      changed_when: false
    - name: 'Ensure test SSL certificate package'
      package:
        name: 'ssl-cert'
        state: 'present'
    - name: 'Ensure hosts entry'
      lineinfile:
        line: '127.0.0.1 revproxy.lab'
        path: '/etc/hosts'
        unsafe_writes: true
    - name: 'Set up reverse proxy'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        nginx_dhparams_size: 1024
    - name: 'Ensure nginx default site listens on port 81'
      lineinfile:
        path: '/etc/nginx/sites-available/default'
        line: "\tlisten 81 default_server;"
        regexp: "\tlisten 8[0-1] default_server;"
    - name: 'Rename default to default.conf'
      file:
        src: '/etc/nginx/sites-available/default'
        dest: '/etc/nginx/sites-enabled/default.conf'
        state: 'link'
      notify: 'restart nginx'
    - name: 'Ensure test content'
      copy:
        content: 'it_works'
        dest: '/var/www/html/index.html'
        mode: 0644
  vars:
    nginx_ocsp: false
    nginx_apps:
      - name: 'revproxy.lab'
        upstream: 'http://localhost:81'
        type: 'simple'
        cert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
        key: '/etc/ssl/private/ssl-cert-snakeoil.key'
        hsts: false
        acme: false
        state: 'present'
  handlers:
    - name: 'restart nginx'
      service:
        name: 'nginx'
        state: 'restarted'
