---
- name: 'Converge'
  hosts: 'all'
  tasks:
    - name: 'Ensure hosts entry'
      ansible.builtin.lineinfile:
        line: '127.0.0.1 revproxy.lab'
        path: '/etc/hosts'
        unsafe_writes: true
    - name: 'Set up reverse proxy'
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    - name: 'Ensure test page config'
      ansible.builtin.copy:
        content: |
          server {
            listen localhost:81;
            root /var/www/html;
            index index.html index.htm;
            location / {
                try_files $uri $uri/ =404;
            }
          }
        dest: '/etc/nginx/sites-enabled/default.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify: 'Restart nginx'
    - name: 'Ensure test content dir'
      ansible.builtin.file:
        path: '/var/www/html'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'
    - name: 'Ensure test content'
      ansible.builtin.copy:
        content: 'it_works'
        dest: '/var/www/html/index.html'
        mode: '0644'
  vars:
    nginx_ocsp: false
    nginx_stream_enabled: true
    nginx_stream_ssh_target: 'localhost:22'
    nginx_apps:
      - name: 'revproxy.lab'
        upstream: 'http://localhost:81'
        type: 'simple'
        cert: '/etc/ssl/certs/server.crt'
        key: '/etc/ssl/certs/server.key'
        hsts: false
        acme: false
        state: 'present'
  handlers:
    - name: 'Restart nginx'
      ansible.builtin.service:
        name: 'nginx'
        state: 'restarted'
